#!/bin/sh
echo '<<<chia_netspace>>>'

CHIA_INSTALLATION_PATH=/home/farmer/chia-blockchain
CHIA_INSTALLATION_USER=farmer

su - ${CHIA_INSTALLATION_USER} -c "${CHIA_INSTALLATION_PATH}/venv/bin/chia farm summary"
